---
driver:
  name: vagrant
  boot_timeout: 1800
  gui: false

provisioner:
  name: chef_zero
  max_retries: 3 # tweak in conjunction with wait_for_retry
  wait_for_retry: 90 # tweak based on machine shutdown speed
  retry_on_exit_code: [35, 213, 259] # retry for array of exit codes

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true
platforms:
  - name: windows-2012r2
    driver:
      customize:
        memory: 4096
  - name: windows-2016
    driver:
      customize:
        memory: 4096
  - name: windows-2019
    driver:
      customize:
        memory: 4096

suites:
  - name: default
    run_list:
      - recipe[chocolatey_server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
